[package]
name = "datademo"
version = "0.1.0"
authors = ["clux"]
edition = "2018"

[dependencies]
envy = "0.4"
serde = { version = "1", features = ["derive"] }
actix-web = "3.2.0"
anyhow = "1.0.34"
env_logger = "0.8.2"
log = "0.4.11"
url = "2.2.0"
